# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('STK', 'Stocks'), ('BND', 'Bonds'), ('CSH', 'Cash Equivalents'), ('ALT', 'Alternatives')], default='STK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('objective', models.CharField(max_length=128)),
                ('risk_tolerance', models.TextField()),
                ('time_frame', models.PositiveSmallIntegerField()),
                ('stock_bond_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('asset_allocation', jsonfield.fields.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=16)),
                ('isin', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=64)),
                ('expense_ratio_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_trade_price', models.DecimalField(decimal_places=4, max_digits=11)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.AssetClass')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=11)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.Account')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.Security')),
            ],
        ),
        migrations.AddField(
            model_name='assetclass',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.Portfolio'),
        ),
    ]
